# Model 2: Diffusion Policy for StackCube-v2
# Diffusion-based policy learning

dataset:
  repo_id: lianqing11/stack_cube_lerobot
  root: ./data/stackcube_v2_1k
# Environment
env:
  type: maniskill
  task: StackCube-v2  # 主训练任务
  obs_mode: rgb
  control_mode: pd_joint_pos
  sim_backend: cpu
  # 多任务评估：在训练过程中同时评估多个任务
  eval_tasks:
    - StackCube-pertube  # 扰动任务
  
policy:
  type: "diffusion"
  push_to_hub: false
  # Diffusion specific parameters
  horizon: 16
  n_action_steps: 8
  n_obs_steps: 2
  num_inference_steps: 10
  
# Training
steps: 100000
batch_size: 8
optimizer:
  lr: 1.0e-5
save_freq: 2000

# Evaluation
eval_freq: 2000
eval:
  n_episodes: 25
  batch_size: 25

# Logging
wandb:
  enable: true
  project: maniskill_lerobot

# Output
output_dir: outputs/diffusion
