# Model 5: Pi0.5 for StackCube-v2
# Physical Intelligence Pi0.5 model (improved version)

experiment:
  name: "stackcube_pi0_5"
  description: "Pi0.5 (Physical Intelligence v0.5) on StackCube-v2"
  tags: ["stackcube", "pi0.5", "vla", "latest"]

dataset:
  repo_id: "lianqing11/stack_cube_lerobot"
  root: "/VLA-Data/scripts/lianqing/projects/ManiSkill/mani_skill/trajectory/output/stackcube_v2_1k"
  
env:
  type: "maniskill"
  task: "StackCube-v2"
  obs_mode: "rgb"
  control_mode: "pd_joint_pos"
  sim_backend: "cpu"
  
policy:
  type: "tdmpc"  # Placeholder - 根据实际的policy type调整
  push_to_hub: false
  # Pi0.5 specific parameters
  use_language: true
  vision_backbone: "vit-large"
  language_model: "phi-2"
  action_head: "flow_matching"
  chunk_size: 64
  use_proprio: true
  
training:
  steps: 150000
  batch_size: 32
  learning_rate: 5e-5
  save_freq: 2000
  gradient_accumulation_steps: 4
  mixed_precision: "fp16"
  
eval:
  enabled: true
  freq: 2000
  n_episodes: 10
  batch_size: 10
  
wandb:
  enable: true
  project: "maniskill_lerobot"
  tags: ["stackcube-v2", "pi0.5"]
  notes: "Pi0.5 improved version"

output:
  base_dir: "outputs/train"
  auto_timestamp: true

